! units
! mm / tonne / seconds
! Newton (tonne*mm/s/s) / MPa (Newton / mm / mm)

fini $ /clear, nostart

/out, curve,out
*vwrite, 'reach', 'height', 'load', 'fwds', 'afts', 'actf', 'actd'
(7A8)
*vwrite, '[mm]', '[mm]', '[t]', '[MPa]', '[MPa]', '[kN]', '[mm]'
(7A8)
/out

*do, j, 1, 10
  
/out, curve,out,,append
*vwrite, 'configuration', j
(A8, F8.0)
/out

*do,i,-20,50,5
fourbar_B, i
fourbar_C, j
*enddo

*enddo
